image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - hugo --baseURL="https://thelazydevops.xyz" && gzip -k -6 $(find public -type f)
  - hugo --baseURL="https://voioo.cz" && gzip -k -6 $(find public -type f)
  artifacts:
    paths:
    - public
  only:
  - master
