baseurl = "https://thelazydevops.xyz"
title = "The Lazy Devops Engineer"

theme = "hugo-coder"

[params]
    author = "Voislav Vasiljevski"
    description = "personal website"
    keywords = "devops,blog,developer,personal"
    info = "DevOps Conjurer"
    avatarurl = "images/avatar.jpg"
    footercontent = "© 2019 · Voislav Vasiljevski, Prague"

[taxonomies]
    series = "series"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
