baseURL = ""
title   = "Voislav Vasiljevski"

DefaultContentLanguage = "en"

theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

# googleAnalytics = ""
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = true
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:title/"

[author]
  name = "Voislav Vasiljevski"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Writing some tutorials, ideas, containers, Linux, Docker ..."
  keywords = "personal,blog,voislav,vasiljevski,lazydevops,containers,tutorials,guides"
  images = [""]

  homeSubtitle = "Google Search expert. Lazy-walking towards the DevOps world"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://gitlab.com/voioo/thelazydevops_xyz/commit/"

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "light"
  themeColor = "#252627"

  [params.logo]
    logoText     = "$ cd /home/"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/ImTheLazyDevops"

  [[params.social]]
    name = "email"
    url  = "mailto:voislav@voioo.cz"

  [[params.social]]
    name = "gitlab"
    url  = "https://gitlab.com/voioo"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/voislavvasiljevski"

[languages]
  [languages.en]
    title = "Voislav Vasiljevski"
    subtitle  = "The Lazy DevOps Blog"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Blog"
    url        = "/posts/"
